// Generated by CoffeeScript 1.12.3
(function() {
  var OnsenList;

  OnsenList = (function() {
    function OnsenList() {
      this.url = require('../OnsenURL').TOP;
      this.cheerio = require('cheerio-httpcli');
    }

    OnsenList.prototype.getList = function(fn) {
      var list;
      list = {};
      return this.cheerio.fetch(this.url, (function(_this) {
        return function(err, $, res) {
          if (err) {
            return fn(null);
          } else {
            $('.listWrap .clr li').each(function() {
              var name, week;
              name = $(this).attr('id');
              week = $(this).attr('data-week');
              if (list[week] === void 0) {
                list[week] = [];
              }
              return list[week].push(name);
            });
            return fn(list);
          }
        };
      })(this));
    };

    return OnsenList;

  })();

  module.exports = new OnsenList();

}).call(this);
