// Generated by CoffeeScript 1.12.3
(function() {
  var OnsenTopics;

  OnsenTopics = (function() {
    function OnsenTopics() {
      this.url = require('../OnsenURL').TOPICS;
      this.xmljson = require('xmljson');
      this.help = require('../help');
    }

    OnsenTopics.prototype.getTopics = function(fn) {
      return this.help.httpRequest(this.url, (function(_this) {
        return function(xml) {
          if (xml !== null) {
            return _this.xmljson.to_json(xml, function(err, json) {
              json = _this.help.castArray(json.rss.channel.item);
              return fn(json);
            });
          } else {
            return fn(null);
          }
        };
      })(this));
    };

    return OnsenTopics;

  })();

  module.exports = new OnsenTopics();

}).call(this);
