// Generated by CoffeeScript 1.12.3
(function() {
  var OnsenSearch;

  OnsenSearch = (function() {
    function OnsenSearch() {
      this.url = require('../OnsenURL').SEARCH;
      this.help = require('../help');
    }

    OnsenSearch.prototype.search = function(keyword, fn) {
      keyword = encodeURIComponent(keyword);
      return this.help.httpRequest(this.url + keyword, (function(_this) {
        return function(jsonp) {
          var json;
          if (jsonp !== null) {
            json = _this.help.catJSONP(jsonp);
            json = JSON.parse(json);
            json = json.result || [];
            return fn(json);
          } else {
            return fn(null);
          }
        };
      })(this));
    };

    return OnsenSearch;

  })();

  module.exports = new OnsenSearch();

}).call(this);
