// Generated by CoffeeScript 1.12.3
(function() {
  var OnsenInfo;

  OnsenInfo = (function() {
    function OnsenInfo() {
      this.url = require('../OnsenURL').GET_INFO;
      this.help = require('../help');
    }

    OnsenInfo.prototype.getInfo = function(name, fn) {
      name = encodeURIComponent(name);
      return this.help.httpRequest(this.url + name, (function(_this) {
        return function(jsonp) {
          var json;
          if (jsonp !== null) {
            json = _this.help.catJSONP(jsonp);
            json = JSON.parse(json);
            if (json.error !== void 0) {
              fn(null);
              return;
            }
            return fn(json);
          } else {
            return fn(null);
          }
        };
      })(this));
    };

    OnsenInfo.prototype.getLink = function(name, fn) {
      return this.getInfo(name, (function(_this) {
        return function(info) {
          var link;
          if (info !== null) {
            link = info.moviePath.pc;
            return fn(link);
          } else {
            return fn(null);
          }
        };
      })(this));
    };

    return OnsenInfo;

  })();

  module.exports = new OnsenInfo();

}).call(this);
