// Generated by CoffeeScript 1.12.3
(function() {
  var OnsenRecommends;

  OnsenRecommends = (function() {
    function OnsenRecommends() {
      this.url_1 = require('../OnsenURL').RECOMMENDS;
      this.url_2 = require('../OnsenURL').DEFAULT;
      this.xmljson = require('xmljson');
      this.help = require('../help');
    }

    OnsenRecommends.prototype.getRecommends = function(fn) {
      return this.help.httpRequest(this.url_1, (function(_this) {
        return function(xml) {
          if (xml !== null) {
            return _this.xmljson.to_json(xml, function(err, data) {
              data = _this.help.castArray(data.recommends.recommend);
              return fn(data);
            });
          } else {
            return fn(null);
          }
        };
      })(this));
    };

    OnsenRecommends.prototype.getRecommendMovie = function(fn) {
      return this.help.httpRequest(this.url_2, (function(_this) {
        return function(jsonp) {
          var json;
          if (jsonp !== null) {
            json = _this.help.catJSONP(jsonp);
            json = JSON.parse(json);
            return fn(json.recommendMovie);
          } else {
            return fn(null);
          }
        };
      })(this));
    };

    OnsenRecommends.prototype.getRecommendGoods = function(fn) {
      return this.help.httpRequest(this.url_2, (function(_this) {
        return function(jsonp) {
          var json;
          if (jsonp !== null) {
            json = _this.help.catJSONP(jsonp);
            json = JSON.parse(json);
            return fn(json.recommendGoods);
          } else {
            return fn(null);
          }
        };
      })(this));
    };

    return OnsenRecommends;

  })();

  module.exports = new OnsenRecommends();

}).call(this);
