// Generated by CoffeeScript 1.12.3
(function() {
  module.exports = {
    catJSONP: function(jsonp) {
      var json;
      json = jsonp.replace(/(callback\(|\);)/g, '');
      return json;
    },
    castArray: function(list) {
      var _list, data, key;
      _list = [];
      for (key in list) {
        data = list[key];
        _list.push(data);
      }
      return _list;
    },
    httpRequest: function(url, fn) {
      var request;
      request = require('request');
      return request(url, (function(_this) {
        return function(err, res, body) {
          if (res.statusCode === 200 && err === null) {
            return fn(body);
          } else {
            return fn(null);
          }
        };
      })(this));
    }
  };

}).call(this);
