// Generated by CoffeeScript 1.12.3
(function() {
  module.exports = {
    TOP: 'http://www.onsen.ag/',
    DEFAULT: 'http://onsen.ag/data/api/getDefaultInfo',
    LIST: 'http://www.onsen.ag/api/shownMovie/shownMovie.json',
    GET_INFO: 'http://www.onsen.ag/data/api/getMovieInfo/',
    SEARCH: 'http://www.onsen.ag/data/api/searchMovie?word=',
    RECOMMENDS: 'http://www.onsen.ag/app/recommends.xml',
    TOPICS: 'http://www.onsen.ag/blog/?feed=rss2'
  };

}).call(this);
