// Generated by CoffeeScript 1.12.3
(function() {
  var OnsenInfo, OnsenList, OnsenRecommends, OnsenSearch, OnsenTopics;

  OnsenList = require('./api/OnsenList');

  OnsenInfo = require('./api/OnsenInfo');

  OnsenSearch = require('./api/OnsenSearch');

  OnsenRecommends = require('./api/OnsenRecommends');

  OnsenTopics = require('./api/OnsenTopics');

  module.exports = {
    getList: function(fn) {
      return OnsenList.getList(fn);
    },
    getInfo: function(name, fn) {
      return OnsenInfo.getInfo(name, fn);
    },
    getLink: function(name, fn) {
      return OnsenInfo.getLink(name, fn);
    },
    search: function(keyword, fn) {
      return OnsenSearch.search(keyword, fn);
    },
    getRecommends: function(fn) {
      return OnsenRecommends.getRecommends(fn);
    },
    getRecommendMovie: function(fn) {
      return OnsenRecommends.getRecommendMovie(fn);
    },
    getRecommendGoods: function(fn) {
      return OnsenRecommends.getRecommendGoods(fn);
    },
    getTopics: function(fn) {
      return OnsenTopics.getTopics(fn);
    }
  };

}).call(this);
